"""Channel-specific response formatting for the Customer Success FTE."""

from enum import Enum


class Channel(str, Enum):
    EMAIL = "email"
    WHATSAPP = "whatsapp"
    WEB_FORM = "web_form"


def format_for_channel(response: str, channel: Channel, ticket_id: str = "") -> str:
    """Format response appropriately for the target channel."""
    if channel == Channel.EMAIL:
        return _format_email(response, ticket_id)
    elif channel == Channel.WHATSAPP:
        return _format_whatsapp(response)
    else:
        return _format_web(response, ticket_id)


def _format_email(response: str, ticket_id: str) -> str:
    return f"""Dear Customer,

Thank you for reaching out to TechCorp Support.

{response}

If you have any further questions, please don't hesitate to reply to this email.

Best regards,
TechCorp AI Support Team
---
Ticket Reference: {ticket_id}
This response was generated by our AI assistant. For complex issues, you can request human support."""


def _format_whatsapp(response: str) -> str:
    if len(response) > 300:
        response = response[:297] + "..."
    return f"{response}\n\nReply for more help or type 'human' for live support."


def _format_web(response: str, ticket_id: str) -> str:
    return f"""{response}

---
Ticket ID: {ticket_id}
Need more help? Reply to this message or visit our support portal."""
